image: "ruby:2.6.2"
services:
  - postgres:latest

variables:
  POSTGRES_DB: database_name

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v # Print out ruby version for debugging
  # - apt-get update -q && apt-get install nodejs -yqq
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

stages:
  - test
  - deploy

rubocop:
  stage: test
  script:
  - bundle exec rubocop

tests:
  stage: test
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    ENT_PARIS_URL: https://ent.parisclassenumerique.fr/cas
    ENT_PARIS_URL_RETOUR: https://demo.dossiersco.fr/retour-ent
  script:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  - bundle exec rails test

demo:
  stage: deploy
  environment:
    name: production
  script:
  - gem install dpl
  - dpl --provider=scalingo --api-token=$SCALINGO_PRODUCTION_KEY --remote=git@scalingo.com:dossiersco-demo.git --branch=HEAD:master
  - curl -O https://cli-dl.scalingo.io/install && bash install
  - scalingo login --api-token $SCALINGO_PRODUCTION_KEY
  - scalingo -a dossiersco-demo run rails db:migrate

production:
  stage: deploy
  environment:
    name: production
  script:
  - gem install dpl
  - dpl --provider=scalingo --api-token=$SCALINGO_PRODUCTION_KEY --remote=git@scalingo.com:dossiersco-production.git --branch=HEAD:master
