image: "ruby:2.6.2"
services:
  - postgres:latest

variables:
  POSTGRES_DB: database_name

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v # Print out ruby version for debugging
  # - apt-get update -q && apt-get install nodejs -yqq
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
  - bundle exec rubocop

rails:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  - bundle exec rails test

deploy:
  type: deploy
  environment: production
  script:
  - gem install dpl
  - dpl --provider=scalingo --api-key=$SCALINGO_PRODUCTION_KEY
