AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/AlignParameters:
  Exclude:
    - 'app/services/pdf_convocation.rb'

LineLength:
  Max: 150
  Exclude:
    - 'app/views/**/*erb*'
    - 'app/models/dossier_eleve.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/controllers/accueil_controller_test.rb'
    - 'test/integration/accueil_controller_test.rb'
    - 'test/integration/inscriptions_controller_test.rb'
    - 'app/controllers/tache_imports_controller.rb'
    - 'app/controllers/configurations_controller.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/dossiers_affelnet_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/jobs/importer_siecle.rb'
    - 'app/controllers/configuration/agents_controller.rb'
    - 'app/models/eleve.rb'
    - 'app/models/etablissement.rb'
    - 'app/models/message.rb'
    - 'app/models/resp_legal.rb'
    - 'app/jobs/importer_affelnet.rb'
    - 'app/services/genere_pdf.rb'
    - 'app/services/contacter_famille.rb'
    - 'lib/tasks/charger_donnees_exemple.rake'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/jobs/importer_siecle.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/models/eleve.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'app/jobs/importer_siecle.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'
    - 'app/controllers/tache_imports_controller.rb'
    - 'app/controllers/configurations_controller.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/suivi_controller.rb'
    - 'app/controllers/dossiers_affelnet_controller.rb'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/controllers/configuration/agents_controller.rb'
    - 'app/controllers/configuration/mef_controller.rb'
    - 'app/models/etablissement.rb'
    - 'app/models/message.rb'
    - 'app/models/resp_legal.rb'
    - 'app/jobs/importer_affelnet.rb'
    - 'app/services/genere_pdf.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/jobs/importer_siecle.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'
    - 'app/controllers/accueil_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/jobs/importer_siecle.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
