AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

LineLength:
  Max: 150
  Exclude:
    - 'app/views/**/*erb*'
    - 'app/models/dossier_eleve.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'app/jobs/importer_siecle.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/ClassLength:
  Max: 170
  Exclude:
    - 'test/**/*'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/jobs/importer_siecle.rb'

Metrics/AbcSize:
  Max: 55
  Exclude:
    - 'test/**/*'
    - 'app/jobs/importer_siecle.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/jobs/importer_siecle.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'app/jobs/importer_siecle.rb'
