AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'


Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

LineLength:
  Max: 100

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'test/system/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 220
