AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 150
  Exclude:

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/jobs/importer_siecle.rb'
    - 'app/controllers/retour_siecles_controller.rb'
    - 'test/services/famille_test.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/contact_par_etats_controller.rb'
    - 'app/services/relancer_dossier.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/dossier_eleve.rb'
    - 'test/controllers/accueil_controller_test.rb'
    - 'test/integration/accueil_controller_test.rb'
    - 'test/integration/inscriptions_controller_test.rb'
    - 'app/controllers/configuration/dossiers_eleve_controller.rb'
    - 'app/controllers/tache_imports_controller.rb'
    - 'app/controllers/configurations_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/dossiers_affelnet_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/controllers/suivi_controller.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/controllers/configuration/agents_controller.rb'
    - 'app/models/eleve.rb'
    - 'app/models/etablissement.rb'
    - 'app/models/message.rb'
    - 'app/models/resp_legal.rb'
    - 'app/jobs/importer_affelnet.rb'
    - 'app/services/genere_pdf.rb'
    - 'app/services/contacter_famille.rb'
    - 'lib/tasks/charger_donnees_exemple.rake'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/pdf_convocation.rb'
    - 'app/services/famille.rb'
    - 'app/services/relancer_dossier.rb'
    - 'app/services/import_nomenclature.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/mailers/famille_mailer.rb'
    - 'app/jobs/export_eleves_xlsx_job.rb'
    - 'app/jobs/export_pieces_jointes_job.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - "app/jobs/export_eleves_xlsx_job.rb"
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/models/dossier_eleve.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/models/eleve.rb'
    - 'app/models/resp_legal.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/integration/accueil_controller_test.rb'
    - 'test/integration/inscriptions_controller_test.rb'
    - 'app/controllers/tache_imports_controller.rb'
    - 'app/controllers/configurations_controller.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/mot_de_passe_agent_controller.rb'
    - 'app/controllers/contact_par_etats_controller.rb'
    - 'app/controllers/pieces_jointes_controller.rb'
    - 'app/controllers/suivi_controller.rb'
    - 'app/controllers/retour_siecles_controller.rb'
    - 'app/controllers/inscriptions_controller.rb'
    - 'app/controllers/configuration/etablissements_controller.rb'
    - 'app/controllers/configuration/agents_controller.rb'
    - 'app/controllers/configuration/mef_controller.rb'
    - 'app/controllers/configuration/exports_controller.rb'
    - 'app/controllers/configuration/dossiers_eleve_controller.rb'
    - 'app/models/etablissement.rb'
    - 'app/models/message.rb'
    - 'app/models/resp_legal.rb'
    - 'app/mailers/famille_mailer.rb'
    - 'app/jobs/export_eleves_xlsx_job.rb'
    - 'app/jobs/importer_siecle.rb'
    - 'app/jobs/export_pieces_jointes_job.rb'
    - 'app/services/pdf_fiche_infirmerie.rb'
    - 'app/services/genere_pdf.rb'
    - 'app/services/relancer_dossier.rb'
    - 'app/services/analyseur_retour_siecle.rb'
    - 'app/services/import_responsables.rb'
    - 'app/services/famille.rb'
    - 'app/services/import_responsables.rb'
    - 'app/services/import_nomenclature.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/services/import_responsables.rb'
    - 'app/services/pdf_convocation.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/retour_siecles_controller.rb'
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/services/analyseur_retour_siecle.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/authentification_cas_ent_controller.rb'
    - 'app/controllers/accueil_controller.rb'
    - 'app/controllers/retour_siecles_controller.rb'
    - 'app/services/import_eleve_complete.rb'
    - 'app/services/analyseur_retour_siecle.rb'

Naming/VariableNumber:
  Enabled: false
