version: '2'

services:
  app:
    build: .
    ports:
      - 9292:9292
      - 9393:9393
    volumes:
      - ./:/app
    command: /bin/bash -lc "sleep 3 && rake db:migrate && bundle exec shotgun -o 0.0.0.0"
    working_dir: /app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
      RUBYOPT: -KU
      RACK_ENV: development
      SESSION_SECRET: notreallysecret
  test:
    build: .
    command: /bin/bash -lc "rm -rf public/uploads/ ; rake db:migrate db:seed && while true; do ruby tests/test*.rb; done"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      POSTGRES_HOST: postgres_test
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
      RUBYOPT: -KU
      RACK_ENV: test
      SESSION_SECRET: notreallysecret
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
