version: '2'

services:
  app:
    image: ruby
    ports:
      - 9292:9292
      - 9393:9393
    volumes:
      - ./:/app
    command: /bin/bash -lc "bundle install && bundle exec shotgun -o 0.0.0.0"
    working_dir: /app
    environment:
      POSTGRES_HOST: postgres
      RUBYOPT: -KU
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dossiersco
      POSTGRES_USER: dossiersco
      POSTGRES_PASSWORD: dossiersco
