source 'https://rubygems.org'
gem 'sinatra'
gem 'shotgun'
gem 'activerecord'
gem 'rack-ssl-enforcer'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'carrierwave'
gem 'fog-aws'
gem 'roo'
gem 'roo-xls'
gem 'bcrypt', '~> 3.1'
gem 'prawn'
gem 'sentry-raven'
gem 'mailjet'
gem 'actionmailer'

group :test do
  gem 'nokogiri'
  gem 'rack-test'
end
